version: "3.8"

services:
  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    environment:
      - POSTGRES_DB=${POSTGRES_KEYCLOAK_DB}
      - POSTGRES_USER=${POSTGRES_KEYCLOAK_USER}
      - POSTGRES_PASSWORD=${POSTGRES_KEYCLOAK_PASSWORD}
    ports:
      - "${POSTGRES_KEYCLOAK_PORT}:5432"
    volumes:
      - pgdata-keycloak:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - postgres-keycloak
    command: start-dev

  postgres-app:
    image: postgres:16
    container_name: postgres-app
    environment:
      - POSTGRES_DB=${POSTGRES_APP_DB}
      - POSTGRES_USER=${POSTGRES_APP_USER}
      - POSTGRES_PASSWORD=${POSTGRES_APP_PASSWORD}
    ports:
      - "${POSTGRES_APP_PORT}:5432"
    volumes:
      - pgdata-app:/var/lib/postgresql/data

volumes:
  pgdata-keycloak:
  pgdata-app:
